const num1 = prompt('Enter your first number:')
const num2 = prompt('Enter your second number:')
const num3 = parseInt(num1,10)
const num4= parseInt(num2,10)
const sum = num3 + num4
document.write('Addition = '+ sum +'<br/>')
const sub = num3 - num4
document.write('subtriction = '+ sub + '<br/>')
const mul = num3 * num4
document.write('Multipication = '+ mul+'<br/>')
const vag = num3 / num4
document.write('vag = ' + vag)
